#!/bin/bash

# 删除未使用的 LV（Logical Volume）
# 删除前会检查 LV 是否挂载，如果挂载则跳过删除
# 使用方法：./remove_unused_lvs.sh [unused_lvs.txt]

set -euo pipefail

# 颜色输出
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# 日志函数
log_info() {
    echo -e "${BLUE}[INFO]${NC} $*"
}

log_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $*"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $*"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $*"
}

# 检查命令是否存在
check_command() {
    if ! command -v "$1" &> /dev/null; then
        log_error "Command '$1' not found. Please install it first."
        exit 1
    fi
}

# 将 LV 名称转换为 device mapper 路径
# LV 名称中的 - 在 device mapper 中变成 --
# VG 和 LV 之间的分隔符是单个 -
# 格式：/dev/mapper/{vg_escaped}-{lv_escaped}
lv_to_device_mapper_path() {
    local vg_name="$1"
    local lv_name="$2"
    
    # 将 VG 和 LV 名称中的 - 替换为 --
    local vg_escaped="${vg_name//-/--}"
    local lv_escaped="${lv_name//-/--}"
    
    # VG 和 LV 之间用单个 - 连接
    echo "/dev/mapper/${vg_escaped}-${lv_escaped}"
}

# 检查 LV 是否挂载
is_lv_mounted() {
    local vg_name="$1"
    local lv_name="$2"
    
    # 获取 device mapper 路径
    local device_path
    device_path=$(lv_to_device_mapper_path "$vg_name" "$lv_name")
    
    # 转义路径中的特殊字符用于 grep
    local escaped_path
    escaped_path=$(echo "$device_path" | sed 's/[[\.*^$()+?{|]/\\&/g')
    
    # 检查是否在 mount 输出中
    # mount 输出格式：/dev/mapper/xxx on /path type filesystem ...
    if mount | grep -qE "^${escaped_path}[[:space:]]+on[[:space:]]+"; then
        return 0  # 已挂载
    else
        return 1  # 未挂载
    fi
}

# 删除单个 LV
remove_lv() {
    local vg_name="$1"
    local lv_name="$2"
    local dry_run="$3"
    
    local lv_path="${vg_name}/${lv_name}"
    
    # 检查 LV 是否存在
    if ! lvs "${lv_path}" &>/dev/null; then
        log_warn "LV $lv_path does not exist, skipping"
        return 1
    fi
    
    # 检查是否挂载
    if is_lv_mounted "$vg_name" "$lv_name"; then
        local device_path
        device_path=$(lv_to_device_mapper_path "$vg_name" "$lv_name")
        local escaped_path
        escaped_path=$(echo "$device_path" | sed 's/[[\.*^$()+?{|]/\\&/g')
        local mount_point
        mount_point=$(mount | grep -E "^${escaped_path}[[:space:]]+on[[:space:]]+" | awk '{print $3}')
        log_warn "LV $lv_path is mounted at $mount_point, skipping deletion"
        return 1
    fi
    
    # 执行删除
    if [[ "$dry_run" == "true" ]]; then
        log_info "[DRY-RUN] Would delete: $lv_path"
        return 0
    else
        log_info "Deleting LV: $lv_path"
        if lvremove -f "$lv_path" 2>/dev/null; then
            log_success "Successfully deleted: $lv_path"
            return 0
        else
            log_error "Failed to delete: $lv_path"
            return 1
        fi
    fi
}

# 主函数
main() {
    local input_file="unused_lvs.txt"
    local dry_run=false
    local verbose=false
    
    # 解析命令行参数
    while [[ $# -gt 0 ]]; do
        case $1 in
            --dry-run)
                dry_run=true
                shift
                ;;
            -v|--verbose)
                verbose=true
                shift
                ;;
            -h|--help)
                echo "Usage: $0 [OPTIONS] [INPUT_FILE]"
                echo ""
                echo "Remove unused LVs from the list generated by scan_unused_lvs.sh"
                echo "Will skip LVs that are currently mounted"
                echo ""
                echo "Arguments:"
                echo "  INPUT_FILE    Input file containing LV list (default: unused_lvs.txt)"
                echo "                Format: vg_name|lv_name (one per line)"
                echo ""
                echo "Options:"
                echo "  --dry-run     Dry run mode: only print what would be deleted"
                echo "  -v, --verbose Verbose output"
                echo "  -h, --help   Show this help message"
                exit 0
                ;;
            -*)
                log_error "Unknown option: $1"
                echo "Use -h or --help for usage information"
                exit 1
                ;;
            *)
                # 第一个非选项参数作为输入文件
                input_file="$1"
                shift
                ;;
        esac
    done
    
    log_info "=========================================="
    log_info "Remove Unused Devbox LVs Script"
    log_info "=========================================="
    
    # 检查必要的命令
    check_command "lvs"
    check_command "lvremove"
    check_command "mount"
    
    # 检查输入文件
    if [[ ! -f "$input_file" ]]; then
        log_error "Input file not found: $input_file"
        log_info "Please run scan_unused_lvs.sh first to generate the list"
        exit 1
    fi
    
    if [[ ! -s "$input_file" ]]; then
        log_warn "Input file is empty: $input_file"
        log_info "No LVs to delete"
        exit 0
    fi
    
    log_info "Reading LV list from: $input_file"
    
    if [[ "$dry_run" == "true" ]]; then
        log_warn "DRY-RUN mode: No LVs will be actually deleted"
    fi
    
    log_info "=========================================="
    
    # 统计信息
    local total_count=0
    local deleted_count=0
    local skipped_mounted=0
    local skipped_not_exist=0
    local failed_count=0
    
    # 读取文件并处理每个 LV
    while IFS='|' read -r vg_name lv_name || [[ -n "$vg_name" ]]; do
        # 跳过空行和注释
        [[ -z "$vg_name" ]] && continue
        [[ "$vg_name" =~ ^# ]] && continue
        
        # 去除空格
        vg_name=$(echo "$vg_name" | xargs)
        lv_name=$(echo "$lv_name" | xargs)
        
        [[ -z "$vg_name" ]] || [[ -z "$lv_name" ]] && continue
        
        total_count=$((total_count + 1))
        
        if remove_lv "$vg_name" "$lv_name" "$dry_run"; then
            deleted_count=$((deleted_count + 1))
        else
            local exit_code=$?
            if is_lv_mounted "$vg_name" "$lv_name"; then
                skipped_mounted=$((skipped_mounted + 1))
            elif ! lvs "${vg_name}/${lv_name}" &>/dev/null; then
                skipped_not_exist=$((skipped_not_exist + 1))
            else
                failed_count=$((failed_count + 1))
            fi
        fi
    done < "$input_file"
    
    log_info "=========================================="
    log_info "Summary:"
    log_info "  Total LVs processed: $total_count"
    if [[ "$dry_run" == "true" ]]; then
        log_info "  Would be deleted: $deleted_count"
    else
        log_info "  Successfully deleted: $deleted_count"
    fi
    log_info "  Skipped (mounted): $skipped_mounted"
    log_info "  Skipped (not exist): $skipped_not_exist"
    if [[ $failed_count -gt 0 ]]; then
        log_warn "  Failed: $failed_count"
    fi
    log_info "=========================================="
    
    if [[ "$dry_run" == "true" ]]; then
        log_info ""
        log_info "To actually delete these LVs, run without --dry-run:"
        log_info "  $0 $input_file"
    fi
}

# 运行主函数
main "$@"

